server:
  port: 8183
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.172:3306/seata-storage?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: seata-storage-service
logging:
  level:
    io:
      seata: info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
seata:
  application-id: ${spring.application.name}
  tx-service-group: default
  service:
    vgroup-mapping:
      default: default
    grouplist:
      default: 127.0.0.1:8091
